### ISSUE TITLE
Browser source in OBS not working

### ISSUE THREAD

**Issue by vojtabiberle** [nhtua/greencam#3] opened 2020-10-31 19:45 UTC
When I'm trying to set up "hard way" of greencam and run OBS with `--enable-gpu --enable-media-stream` params and use Browser source, app is still loading and in cosole are those two errors:

```
[1031/203957.018223:INFO:CONSOLE(31)] "Something went wrong!", source: https://greencam.netlify.app/app.js (31)
[1031/203957.018351:INFO:CONSOLE(32)] "[object DOMException]", source: https://greencam.netlify.app/app.js (32)
```

OBS version: 25.0.8-2 (linux)
Browser version: obs-linuxbrowser-bin 0.6.1-1

**Comment by edurenye** [comment] 2020-12-19 12:26
For me works fine with `obs --use-fake-ui-for-media-stream --enable-gpu --enable-media-stream` in OBS 26.1.

**Comment by PeterKW** [comment] 2021-01-06 16:12
I don't know if this is related but when I load it in the browser I get endless loading and these errors in the console:
failed to load resource: net::ERR_FILE_NOT_FOUND
body-pix.min.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
bluebird.min.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
app.js:84 Uncaught ReferenceError: bodyPix is not defined
    at initMLModel (app.js:84)
    at HTMLVideoElement.video.onloadeddata (app.js:71)
initMLModel @ app.js:84
video.onloadeddata @ app.js:71

![image](https://user-images.githubusercontent.com/13779157/103791218-17a5d000-503a-11eb-9c35-c3803fdb2969.png)

**Comment by vojtabiberle** [comment] 2021-01-07 09:52
> For me works fine with `obs --use-fake-ui-for-media-stream --enable-gpu --enable-media-stream` in OBS 26.1.

Now works for me too (with new OBS 26.1 with building browser)

**Comment by nhtua** [comment] 2021-01-07 16:06
@PeterKW Looks like you need to run `npm install` first.

**Comment by nhtua** [comment] 2021-01-07 16:07
@vojtabiberle I close this issue since I couldn't reproduce the error on my side, and it also works on your new OBS 26.1.

**Closed as completed by nhtua** 2021-01-07 16:07 UTC
Labels: help wanted
